In [2]:
import pandas as pd
df= pd.read_csv("Combined_dataset.csv")

In [3]:
df.head(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.tail(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
df.shape

(1000, 24)

In [6]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [7]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [8]:
df.info

<bound method DataFrame.info of      product_id           title  \
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

                                   product_description  rating  ratings_count  \
0                       Women Navy Blue Solid Backpack     3.8             15
1                    Unisex Navy Blue Striped Backpack     4.5             67
2                       Aries Women Pink Mini Backpack     4.4            226
3           Unisex Navy & Grey Printed Burner Backpack     4.4           1052
4                             Men Blue Solid Bath Robe     4.7             12
..                                                 ...     ...            ...
995  Men FORTE Silver Automatic Skeleton Analogue W...     3.5             11
996  Women White Patterned Dial & White Straps Anal...     5.0             22
997  Women Rose Gold-Toned Mirrored Analogue Watch ...     2.8              5
998  Men Black Brass Dial & Black Stainless Steel S...     4.3             17
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount   final_price currency  \
0             3995      58.0   "₹3,995.00"      INR
1             2899      35.0   "₹2,899.00"      INR
2             2999      65.0   "₹2,999.00"      INR
3             1675      52.0   "₹1,675.00"      INR
4             2899      17.0   "₹2,899.00"      INR
..             ...       ...           ...      ...
995          11890      50.0  "₹11,890.00"      INR
996           8900      45.0   "₹8,900.00"      INR
997           7950      50.0   "₹7,950.00"      INR
998           3295      20.0   "₹2,636.00"      INR
999            699      31.0     "₹699.00"      INR

                                                images  ...  \
0    http://assets.myntassets.com/assets/images/837...  ...
1    http://assets.myntassets.com/assets/images/913...  ...
2    http://assets.myntassets.com/assets/images/176...  ...
3    http://assets.myntassets.com/assets/images/137...  ...
4    http://assets.myntassets.com/assets/images/pro...  ...
..                                                 ...  ...
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
0    {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1    {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2    {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3    {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4    {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
..                                                 ...                 ...
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                                              sizes  \
0               NaN                               [{"size":"Onesize"}]
1               NaN                               [{"size":"Onesize"}]
2               NaN                                     [{"size":"S"}]
3               NaN                               [{"size":"Onesize"}]
4               NaN  [{"size":"M","value":"45.0in","value_name":"Fr...
..              ...                                                ...
995             NaN                               [{"size":"Onesize"}]
996             NaN                               [{"size":"Onesize"}]
997             NaN                               [{"size":"Onesize"}]
998  Tru███m R███il                               [{"size":"Onesize"}]
999             NaN                                [{"size":"Medium"}]

                                                videos  \
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
..                                                 ...
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                                      variations  \
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                            NaN
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
..                                           ...
995                                          NaN
996                                          NaN
997                    [{},{},{},{},{},{},{},{}]
998                                          NaN
999                                [{},{},{},{}]

                                            best_offer  \
0                                                   {}
1                                                   {}
2                                                   {}
3                                                   {}
4                                                   {}
..                                                 ...
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
0    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4    [{"offer_name":"10% Instant Discount on IndusI...  bath-robe
..                                                 ...        ...
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[1000 rows x 24 columns]>

In [9]:
#checking for null values
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [9]:
#filled all the null with unknown values 
df.fillna(0, inplace=True)

In [16]:
# checking the updated file
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [10]:
#Select columns
selected_data = df[["category", "rating"]]
print(selected_data.head(20))
#Filter rows
filtered_data = df[df["category"] == 'dresses']
print(filtered_data.head())

                category  rating
0              backpacks     3.8
1              backpacks     4.5
2              backpacks     4.4
3              backpacks     4.4
4              bath-robe     4.7
5   bathroom-accessories     4.5
6            bath-towels     4.0
7              bedsheets     4.7
8              bedsheets     4.5
9              bedsheets     3.7
10             bedsheets     4.4
11             bedsheets     0.0
12             bedsheets     0.0
13             bedsheets     3.9
14             bedsheets     3.6
15             bedsheets     4.5
16             bedsheets     3.8
17             bedsheets     4.3
18                 belts     3.8
19              bodysuit     4.1
    product_id        title  \
90    21664722   Curvy Clan
91    21426422     Trendyol
92    21238004  COVER STORY
93    21426632     Trendyol
94    21673378       RACHNA

                                  product_description  rating  ratings_count  \
90             Colourblocked A-Line Cotton Maxi Dress     3.7              3
91                                   Black Maxi Dress     4.1             10
92    Embellished Shoulder Straps Velvet Sheath Dress     4.8             24
93    Floral Printed Shoulder strap A-Line Mini Dress     3.9             35
94  Floral Print Flared Sleeve Crepe A-Line Mini D...     3.0              4

    initial_price  discount  final_price currency  \
90           2999       0.0  "₹2,999.00"      INR
91           4399      45.0  "₹2,419.00"      INR
92           3490      40.0  "₹2,094.00"      INR
93           3599      30.0  "₹2,519.00"      INR
94           1299      51.0    "₹628.00"      INR

                                               images  ...  \
90  http://assets.myntassets.com/assets/images/216...  ...
91  http://assets.myntassets.com/assets/images/214...  ...
92  http://assets.myntassets.com/assets/images/212...  ...
93  http://assets.myntassets.com/assets/images/214...  ...
94  http://assets.myntassets.com/assets/images/216...  ...

                                      amount_of_stars  \
90  {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...
91  {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...
92  {"1_star":1,"2_stars":0,"3_stars":0,"4_stars":...
93  {"1_star":6,"2_stars":2,"3_stars":1,"4_stars":...
94  {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...

                                  what_customers_said  \
90                                                  0
91  [{"percentage":"100","value_name":"Fit, Just R...
92  [{"percentage":"100","value_name":"Fit, A Litt...
93                                                  0
94                                                  0

                       seller_name  \
90                    RUB███S C███
91                    Sup███om ███
92  Cov███Sto███Clo█████████ite███
93                    Sup███om ███
94  RAC███ AR███RIN█████████TD.███

                                                sizes videos  \
90  [{"size":"XL","value":"42.0in","value_name":"B...      0
91  [{"size":"XS","value":"32.0in","value_name":"T...      0
92  [{"size":"XS","value":"32.0in","value_name":"T...      0
93  [{"size":"XS","value":"32.0in","value_name":"T...      0
94  [{"size":"M","value":"38.0in","value_name":"Bu...      0

                                   seller_information variations  \
90  604███TH ███OR,█████████ITA███████████████████...          0
91  Plo███o- ███ 1s█████████Sui███████████████████...          0
92  Kil███5/1███ 18█████████ 22███████████████████...          0
93  Plo███o- ███ 1s█████████Sui███████████████████...          0
94   243███244███ Pa█████████rat█████████████████████          0

                                           best_offer  \
90  {"applicable_on":"Orders above Rs. 1499 (only ...
91  {"applicable_on":"Orders above Rs. 1499 (only ...
92  {"applicable_on":"Orders above Rs. 1499 (only ...
93  {"applicable_on":"Orders above Rs. 1499 (only ...
94  {"applicable_on":"Orders above Rs. 649 (only o...

                                          more_offers category
90  [{"offer_name":"10% Instant Discount on IndusI...  dresses
91  [{"offer_name":"10% Instant Discount on IndusI...  dresses
92  [{"offer_name":"10% Instant Discount on IndusI...  dresses
93  [{"offer_name":"10% Instant Discount on IndusI...  dresses
94  [{"offer_name":"10% Instant Discount on IndusI...  dresses

[5 rows x 24 columns]

In [11]:
df.duplicated().sum() 
#there are no duplicate rows in the csv file

np.int64(0)

In [13]:
df["discount_amount"] = df["initial_price"] * (df["discount"] / 100)

In [14]:
df.to_csv("cleaned_dataset.csv", index=False)